import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {createEngine} from "../dist/engine.mjs";
import {opticalSpectrum,convergence,parseDielectricCSV,sampleCSV,applyParameters,defaults,diamondFractional,safeFilename} from "../dist/physics.mjs";
import {lessons} from "../dist/lessons.mjs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
assert.equal(diamondFractional.length,8);
assert.ok(Math.abs(Math.sqrt(3)*5.431/4-2.35169198398)<1e-8);
const spectrum=opticalSpectrum(defaults.optics);
assert.ok(Math.abs(spectrum[0].re-(1+12/3.4**2))<1e-12);
assert.ok(spectrum.every(r=>r.loss>=0 && r.im>=0 && Number.isFinite(r.re)));
assert.equal(convergence(2).cutoff,450);
assert.equal(convergence(.5).cutoff,null);
assert.equal(convergence(5).cutoff,400);
assert.equal(parseDielectricCSV(sampleCSV()).length,201);
assert.equal(parseDielectricCSV("E,Re,Im,ReLF,ImLF\n0,1,0,1,0\n1,2,1,2,1").length,2);
assert.throws(()=>parseDielectricCSV("0,1,0\n1,2,1"));
assert.throws(()=>parseDielectricCSV("1,1,0,1,0\n0,2,1,2,1"));
assert.throws(()=>parseDielectricCSV("0,1,0,1,0\n1,NaN,1,2,1"));
assert.equal(safeFilename("../../demo.py"),"demo.py");
assert.equal(applyParameters("x = 1  # @x\n",{x:3}).trim(),"x = 3  # @x");
console.log("Physics and CSV checks passed.");
const engine=await createEngine({indexURL:path.join(root,"dist/runtime/"),runnerSource:await fs.readFile(path.join(root,"dist/runner.py"),"utf8"),onStatus:console.log});
engine.writeFiles([{name:"df.csv",data:sampleCSV()}]);
console.log("Actual Pyodide Python:",engine.version);
for(const lesson of lessons.filter(l=>l.id!=="gpaw")){
  const code=applyParameters(await fs.readFile(path.join(root,"dist/examples",lesson.filename),"utf8"),defaults[lesson.id]);
  const r=await engine.run(code,lesson.filename);
  assert.equal(r.error,null,r.error);
  assert.ok(r.figures.length>0,"Expected real PNG output for "+lesson.id);
  const png=Buffer.from(r.figures[0],"base64");
  assert.equal(png.subarray(1,4).toString(),"PNG");
  await fs.mkdir(path.join(root,".sites-runtime/qa"),{recursive:true});
  await fs.writeFile(path.join(root,".sites-runtime/qa",lesson.id+".png"),png);
  console.log(lesson.id,"PASS",r.figures.length,"figure(s)",r.output.trim());
}
const result=await engine.run("import scipy\nfrom scipy.integrate import quad\nprint(quad(lambda x: x*x, 0, 1)[0])\nprint(6*7)","uploaded.py");
assert.equal(result.error,null);assert.match(result.output,/0.333333333333333/);assert.match(result.output,/42/);
const failure=await engine.run("raise ValueError('intentional test')","bad.py");
assert.match(failure.error,/intentional test/);
const recovery=await engine.run("print('recovered')","recovery.py");
assert.equal(recovery.error,null);assert.match(recovery.output,/recovered/);
const saved=await engine.run("import matplotlib.pyplot as plt\nplt.plot([0,1],[0,1])\nplt.savefig('saved.svg')\nplt.close()\nwith open('answer.txt','w') as f: f.write('42')","save.py");
assert.equal(saved.error,null);assert.ok(saved.artifacts.some(a=>a.name==="saved.svg"));assert.ok(saved.artifacts.some(a=>a.name==="answer.txt"));
console.log("Uploaded script, SciPy, error recovery and saved artifacts passed.");
